services:

  redis_cache:
    image: redis:7
    container_name: redis_cache
    expose:
      - "6379"
    networks:
      - user_net
    # Non usiamo un volume per la cache di idempotenza, dato che è volatile e gestita con TTL.

  mysql_user_db:
    image: mysql:8.0
    container_name: user_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: usermanager_db
      MYSQL_USER: usermgr
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
    expose:
      - "3306"
    volumes:
      - user_db_data:/var/lib/mysql
      - ./user_manager/init_user_db.sql:/docker-entrypoint-initdb.d/init_user_db.sql
    networks:
      - user_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "--silent" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 30s

  user_manager:
    build: ./user_manager
    container_name: user_manager
    depends_on:
      mysql_user_db:
        condition: service_healthy
      redis_cache:
        condition: service_started
    restart: always
    environment:
      MYSQL_HOST: mysql_user_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: usermanager_db
      MYSQL_USER: usermgr
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      LISTEN_PORT: 5003
      DATACOLLECTOR_BASE_URL: http://data_collector:5002
    ports:
      - "50051:50051"
    expose:
      - "5003"
    networks:
      - user_net
      - gRPC_net
      - gateway_net

  mysql_data_db:
    image: mysql:8.0
    container_name: data_collector_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: data_db
      MYSQL_USER: userdt
      MYSQL_PASSWORD: ${DATA_DB_PASSWORD}
    expose:
      - "3306"
    volumes:
      # volume
      - data_db_data:/var/lib/mysql
      # Eseguiamo uno script SQL all'avvio per creare la tabella
      - ./data_collector/init_data_db.sql:/docker-entrypoint-initdb.d/init_data_db.sql
    networks:
      - data_collector_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "--silent" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 30s

  data_collector:
    build: ./data_collector
    container_name: data_collector
    depends_on:
      mysql_data_db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: always
    environment:
      MYSQL_HOST: mysql_data_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: data_db
      MYSQL_USER: userdt
      MYSQL_PASSWORD: ${DATA_DB_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      USER_MANAGER_HOST: user_manager
      USER_MANAGER_PORT: 50051
      LISTEN_PORT: 5002
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      OPENSKY_CB_FAILURE_THRESHOLD: 5
      OPENSKY_CB_RECOVERY_TIMEOUT: 30
    expose:
      - "5002"
    networks:
      - data_collector_net
      - gRPC_net
      - kafka_net
      - gateway_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: ULLsQw4xTkWRCNPMvcwf5g
      KAFKA_CLUSTER_ID: ULLsQw4xTkWRCNPMvcwf5g
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_LOG4J_LOGGERS: org.apache.kafka.image.loader.MetadataLoader=WARN

      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka_net
    healthcheck:
      test: ["CMD", "bash", "-lc", "/usr/bin/kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  kafka-setup:
    build: ./kafka
    container_name: kafka-setup
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"
    networks:
      - kafka_net

  alert_system:
    build: ./alert_system
    container_name: alert_system
    depends_on:
      mysql_data_db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: mysql_data_db
      DB_PORT: 3306
      DB_NAME: data_db
      DB_USER: userdt
      DB_PASSWORD: ${DATA_DB_PASSWORD}
    networks:
      - kafka_net
      - data_collector_net

  alert_notifier_system:
    build: ./alert_notifier_system
    container_name: alert_notifier_system
    depends_on:
      kafka:
        condition: service_started
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025
    networks:
      - kafka_net
      - mailhog_net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mailhog_net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/SSL_certificate/nginx-selfsigned.crt:/etc/nginx/ssl/nginx.selfsigned.crt
      - ./gateway/SSL_certificate/nginx-selfsigned.key:/etc/nginx/ssl/nginx.selfsigned.key
    depends_on:
      - user_manager
      - data_collector
    networks:
      - gateway_net


volumes:
  user_db_data:
  data_db_data:
  kafka-data:

networks:
  user_net:
  data_collector_net:
  gRPC_net:
  kafka_net:
  mailhog_net:
  gateway_net:
