services:

  redis_cache:
    image: redis:7
    container_name: redis_cache
    expose:
      - "6379"
    networks:
      - user_net
    # Non usiamo un volume per la cache di idempotenza, dato che è volatile e gestita con TTL.

  mysql_user_db:
    image: mysql:8.0
    container_name: user_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: usermanager_db
      MYSQL_USER: usermgr
      MYSQL_PASSWORD: usermgrpwd
    expose:
      - "3306"
    volumes:
      - user_db_data:/var/lib/mysql
      - ./user_manager/init_user_db.sql:/docker-entrypoint-initdb.d/init_user_db.sql
    networks:
      - user_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "--silent" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 30s

  user_manager:
    build: ./user_manager
    container_name: user_manager
    depends_on:
      mysql_user_db:
        condition: service_healthy
      redis_cache:
        condition: service_started
    restart: always
    environment:
      MYSQL_HOST: mysql_user_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: usermanager_db
      MYSQL_USER: usermgr
      MYSQL_PASSWORD: usermgrpwd
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      LISTEN_PORT: 5003
      DATACOLLECTOR_BASE_URL: http://data_collector:5002
    ports:
      - "5003:5003"
      - "50051:50051"
    networks:
      - user_net
      - shared_microservices_net

  mysql_data_db:
    image: mysql:8.0
    container_name: data_collector_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: data_db
      MYSQL_USER: userdt
      MYSQL_PASSWORD: userdtpwd
    expose:
      - "3306"
    volumes:
      # volume
      - data_db_data:/var/lib/mysql
      # Eseguiamo uno script SQL all'avvio per creare la tabella
      - ./data_collector/init_data_db.sql:/docker-entrypoint-initdb.d/init_data_db.sql
    networks:
      - data_collector_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "--silent" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 30s

  data_collector:
    build: ./data_collector
    container_name: data_collector
    depends_on:
      mysql_data_db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: always
    environment:
      MYSQL_HOST: mysql_data_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: data_db
      MYSQL_USER: userdt
      MYSQL_PASSWORD: userdtpwd
      CLIENT_ID: rg32-api-client
      CLIENT_SECRET: 8WeYB3x0xz5W7KPghf5rSgziS0TfNsJZ
      USER_MANAGER_HOST: user_manager
      USER_MANAGER_PORT: 50051
      LISTEN_PORT: 5002
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      OPENSKY_CB_FAILURE_THRESHOLD: 5
      OPENSKY_CB_RECOVERY_TIMEOUT: 30
    ports:
      - "5002:5002"
    networks:
      - data_collector_net
      - shared_microservices_net
      - kafka_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: ULLsQw4xTkWRCNPMvcwf5g
      KAFKA_CLUSTER_ID: ULLsQw4xTkWRCNPMvcwf5g
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_LOG4J_LOGGERS: org.apache.kafka.image.loader.MetadataLoader=WARN
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka_net

  kafka-setup:
    build: ./kafka
    container_name: kafka-setup
    depends_on:
      - kafka
    restart: "no"
    networks:
      - kafka_net

  alert_system:
    build: ./alert_system
    container_name: alert_system
    depends_on:
      mysql_data_db:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DB_HOST: mysql_data_db
      DB_PORT: 3306
      DB_NAME: data_db
      DB_USER: userdt
      DB_PASSWORD: userdtpwd
    networks:
      - kafka_net
      - data_collector_net


volumes:
  user_db_data:
  data_db_data:
  kafka-data:

networks:
  user_net:
  data_collector_net:
  shared_microservices_net:
  kafka_net:
