version: "3.9"

services:
  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: usermanager_db
      MYSQL_USER: usermgr
      MYSQL_PASSWORD: usermgrpwd
    ports:
      - "3306:3306"   # opzionale, per accedere da host
    volumes:
      - user-db-data:/var/lib/mysql

  flight-db:
    image: mysql:8
    container_name: flight-db
    environment:
      MYSQL_ROOT_PASSWORD: flightrootpwd
      MYSQL_DATABASE: flightdata_db
      MYSQL_USER: flightuser
      MYSQL_PASSWORD: flightpwd
    ports:
      - "3307:3306"   # opzionale, per accedere da host
    volumes:
      - flight-db-data:/var/lib/mysql

  user-manager-grpc:
    build:
      context: .
      dockerfile: user-manager/Dockerfile
    container_name: user-manager-grpc
    environment:
      USER_DB_HOST: user-db
      USER_DB_PORT: "3306"
      USER_DB_NAME: usermanager_db
      USER_DB_USER: usermgr
      USER_DB_PASSWORD: usermgrpwd
    depends_on:
      - user-db
    restart: on-failure
    command: ["python", "server.py"]

  user-manager-app:
    build:
      context: .
      dockerfile: user-manager/Dockerfile
    container_name: user-manager-app
    environment:
      USER_DB_HOST: user-db
      USER_DB_PORT: "3306"
      USER_DB_NAME: usermanager_db
      USER_DB_USER: usermgr
      USER_DB_PASSWORD: usermgrpwd
      DATACOLLECTOR_BASE_URL: http://data-collector:5000
    depends_on:
      - user-db
      - data-collector
    command: ["python", "app.py"]
    ports:
      - "8000:8000"

  data-collector:
    build:
      context: .
      dockerfile: data-collector/Dockerfile
    container_name: data-collector
    environment:
      FLIGHT_DB_HOST: flight-db
      FLIGHT_DB_PORT: "3306"
      FLIGHT_DB_NAME: flightdata_db
      FLIGHT_DB_USER: flightuser
      FLIGHT_DB_PASSWORD: flightpwd

      USERMANAGER_GRPC_HOST: user-manager-grpc
      USERMANAGER_GRPC_PORT: "50051"

      # OpenSky OAuth2
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
    depends_on:
      - flight-db
      - user-manager-grpc
    ports:
      - "5000:5000"

volumes:
  user-db-data:
  flight-db-data:
