events {}

http {
  server {
    listen 80;
    server_name progettoeternograsso.com;

    # (opzionale) limite body
    client_max_body_size 2m;

    # USER MANAGER
    location /api/users/ {
      proxy_pass http://user_manager:5003/;
      proxy_set_header Host $host;
    }

    # DATA COLLECTOR
    location /api/data/ {
      proxy_pass http://data_collector:5002/;
      proxy_set_header Host $host;
    }

    # healthcheck semplice
    location /health {
      return 200 "ok\n";
    }
  }
}
