# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_manager.proto\x12\x0busermanager\"3\n\x04User\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\n\n\x02\x43\x46\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"6\n\x13RegisterUserRequest\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.usermanager.User\"4\n\x11\x44\x65leteUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x0cUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x16\x43heckUserExistsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\")\n\x17\x43heckUserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\x81\x02\n\x0bUserManager\x12K\n\x0cRegisterUser\x12 .usermanager.RegisterUserRequest\x1a\x19.usermanager.UserResponse\x12G\n\nDeleteUser\x12\x1e.usermanager.DeleteUserRequest\x1a\x19.usermanager.UserResponse\x12\\\n\x0f\x43heckUserExists\x12#.usermanager.CheckUserExistsRequest\x1a$.usermanager.CheckUserExistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=35
  _globals['_USER']._serialized_end=86
  _globals['_REGISTERUSERREQUEST']._serialized_start=88
  _globals['_REGISTERUSERREQUEST']._serialized_end=142
  _globals['_DELETEUSERREQUEST']._serialized_start=144
  _globals['_DELETEUSERREQUEST']._serialized_end=196
  _globals['_USERRESPONSE']._serialized_start=198
  _globals['_USERRESPONSE']._serialized_end=246
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_start=248
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_end=287
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_start=289
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_end=330
  _globals['_USERMANAGER']._serialized_start=333
  _globals['_USERMANAGER']._serialized_end=590
# @@protoc_insertion_point(module_scope)
