# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_manager.proto\x12\x0busermanager\"\'\n\x16\x43heckUserExistsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\")\n\x17\x43heckUserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\">\n\x1b\x43heckUserCredentialsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\x1c\x43heckUserCredentialsResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\xd8\x01\n\x0bUserManager\x12\\\n\x0f\x43heckUserExists\x12#.usermanager.CheckUserExistsRequest\x1a$.usermanager.CheckUserExistsResponse\x12k\n\x14\x43heckUserCredentials\x12(.usermanager.CheckUserCredentialsRequest\x1a).usermanager.CheckUserCredentialsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_start=35
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_end=74
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_start=76
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_end=117
  _globals['_CHECKUSERCREDENTIALSREQUEST']._serialized_start=119
  _globals['_CHECKUSERCREDENTIALSREQUEST']._serialized_end=181
  _globals['_CHECKUSERCREDENTIALSRESPONSE']._serialized_start=183
  _globals['_CHECKUSERCREDENTIALSRESPONSE']._serialized_end=228
  _globals['_USERMANAGER']._serialized_start=231
  _globals['_USERMANAGER']._serialized_end=447
# @@protoc_insertion_point(module_scope)
