# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import user_manager_pb2 as user__manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserManagerStub(object):
    """Servizio usato tra microservizi (UserManager <-> DataCollector)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckUserExists = channel.unary_unary(
                '/usermanager.UserManager/CheckUserExists',
                request_serializer=user__manager__pb2.CheckUserExistsRequest.SerializeToString,
                response_deserializer=user__manager__pb2.CheckUserExistsResponse.FromString,
                _registered_method=True)
        self.CheckUserCredentials = channel.unary_unary(
                '/usermanager.UserManager/CheckUserCredentials',
                request_serializer=user__manager__pb2.CheckUserCredentialsRequest.SerializeToString,
                response_deserializer=user__manager__pb2.CheckUserCredentialsResponse.FromString,
                _registered_method=True)


class UserManagerServicer(object):
    """Servizio usato tra microservizi (UserManager <-> DataCollector)

    """

    def CheckUserExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckUserExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserExists,
                    request_deserializer=user__manager__pb2.CheckUserExistsRequest.FromString,
                    response_serializer=user__manager__pb2.CheckUserExistsResponse.SerializeToString,
            ),
            'CheckUserCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserCredentials,
                    request_deserializer=user__manager__pb2.CheckUserCredentialsRequest.FromString,
                    response_serializer=user__manager__pb2.CheckUserCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usermanager.UserManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usermanager.UserManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserManager(object):
    """Servizio usato tra microservizi (UserManager <-> DataCollector)

    """

    @staticmethod
    def CheckUserExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usermanager.UserManager/CheckUserExists',
            user__manager__pb2.CheckUserExistsRequest.SerializeToString,
            user__manager__pb2.CheckUserExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usermanager.UserManager/CheckUserCredentials',
            user__manager__pb2.CheckUserCredentialsRequest.SerializeToString,
            user__manager__pb2.CheckUserCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
