apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system-deployment
  labels:
    app: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      restartPolicy: Always
      containers:
        - name: alert-system
          image: alert-system:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: DB_HOST
              value: "data-db-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "data_db"
            - name: DB_USER
              value: "userdt"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-db-psw
                  key: mysql_password

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi