apiVersion: v1
kind: Secret
metadata:
  name: opensky-credentials
type: Opaque
data:
  client_id: cmczMi1hcGktY2xpZW50 # Codifica in Base64 della password (rg32-api-client)
  client_secret: OFdlWUIzeDB4ejVXN0tQZ2hmNXJTZ3ppUzBUZk5zSlo=  # Codifica in Base64 della password (8WeYB3x0xz5W7KPghf5rSgziS0TfNsJZ)