apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-deployment
  labels:
    app: user-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      restartPolicy: Always
      containers:
        - name: user-manager
          image: user-manager:latest # dare questo nome all'immagine
          imagePullPolicy: Never # da tenere così in produzione e scambiare con IfNotPresent quando sarà pronta
          ports:
            - name: api-port
              containerPort: 5003
            - name: grpc-port
              containerPort: 50051
            - name: metrics-port
              containerPort: 9999
          env:
            - name: MYSQL_HOST
              value: "user-db-service" # Nome del Service K8s di MySQL
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "usermanager_db"
            - name: MYSQL_USER
              value: "usermgr"
            - name: REDIS_HOST
              value: "redis-service" # Nome del Service K8s di Redis
            - name: REDIS_PORT
              value: "6379"
            - name: LISTEN_PORT
              value: "5003"
            - name: DATACOLLECTOR_BASE_URL
              value: "http://data-collector-service:80"


            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-psw
                  key: mysql_password

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName # Prende il nome del nodo reale dove gira

          readinessProbe:
            tcpSocket:
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5003
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: user-manager-service
  labels:
    app: user-manager-service
spec:
  ports:
    - name: api-port
      protocol: TCP
      port: 80 # porta del servizio
      targetPort: 5003 # porta esposta dal container
    - name: grpc-port
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics-port
      protocol: TCP
      port: 9999 # porta del servizio
      targetPort: 9999 # porta esposta dal container
  selector:
    app: user-manager