# mongo .yaml completo di persistenza
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-deployment
  labels:
    app: user-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-psw
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              value: "usermanager_db"
            - name: MYSQL_USER
              value: "usermgr"
            - name: MYSQL_PASSWORD
              valueFrom:
                    secretKeyRef:
                      name: user-db-psw
                      key: mysql_password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d/init_user_db.sql
              subPath: init_user_db.sql

          # Sostituto del Healthcheck di Docker Compose
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)" ]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)" ]
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: user-db-pvc
        - name: init-script-volume
          configMap:
            name: user-db-init-script # ConfigMap

---
apiVersion: v1
kind: Service
metadata:
  name: user-db-service
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 3306 # porta esposta dal servizio
      targetPort: 3306 # porta esposta dal container