# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_manager.proto\"\'\n\x16\x43heckUserExistsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\")\n\x17\x43heckUserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\">\n\x1b\x43heckUserCredentialsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"-\n\x1c\x43heckUserCredentialsResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\xa8\x01\n\x0bUserManager\x12\x44\n\x0f\x43heckUserExists\x12\x17.CheckUserExistsRequest\x1a\x18.CheckUserExistsResponse\x12S\n\x14\x43heckUserCredentials\x12\x1c.CheckUserCredentialsRequest\x1a\x1d.CheckUserCredentialsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_start=22
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_end=61
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_start=63
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_end=104
  _globals['_CHECKUSERCREDENTIALSREQUEST']._serialized_start=106
  _globals['_CHECKUSERCREDENTIALSREQUEST']._serialized_end=168
  _globals['_CHECKUSERCREDENTIALSRESPONSE']._serialized_start=170
  _globals['_CHECKUSERCREDENTIALSRESPONSE']._serialized_end=215
  _globals['_USERMANAGER']._serialized_start=218
  _globals['_USERMANAGER']._serialized_end=386
# @@protoc_insertion_point(module_scope)
